### ISSUE TITLE
Doesn't work at all.

### ISSUE THREAD

**Issue by ghost** [GUSecLab/tor-exit-relays#1]
Hi !

This doesn't work at all . No matter what I try, it doesn't work.

![VirtualBox_kubuntu_14_03_2023_14_51_10](https://user-images.githubusercontent.com/65355324/225023914-22ef49c4-b6af-466a-a810-ffac23d46975.png)
![VirtualBox_kubuntu_14_03_2023_14_53_21](https://user-images.githubusercontent.com/65355324/225023944-9bb81eaa-1147-4111-b81b-aa3e0116a4c8.png)

**Comment by zz090923610** [comment]
Thanks for evaluating our work! If you are trying with the EEBT demo, which is based on AWS, that should not work since it has not been maintained for years, and since we are not a company, we currently don't operate any bridges. If you need more evaluations, please set up the AWS backend with your accounts; free-tier VMs should work fine. Thanks again for your evaluation. Please let us know if you have further questions!
